apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
  labels:
    app.kubernetes.io/name: prometheus
    name: prometheus-configuration
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
    scrape_configs:
    - job_name: oep-e2e
      metrics_path: /metrics/e2e
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - e2e-metrics
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        regex: true
        action: keep