---
# This StatefulSet deploys e2e-metrics controller
# This makes use of configmaps loaded with test yaml
# files that are useful for testing purposes only.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: e2e-metrics
  name: e2e-metrics
  namespace: e2e-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      name: e2e-metrics
  serviceName: ""
  template:
    metadata:
      labels:
        name: e2e-metrics
    spec:
      serviceAccountName: e2e-metrics
      containers:
      - name: e2e-metrics
        image: amitnist/e2e-metrics:ci
        imagePullPolicy: Always
        command: ["/usr/bin/e2e-metrics"]
        args:
        - --logtostderr
        - --run-as-local
        - -v=5
        - --discovery-interval=40s
        - --cache-flush-interval=240s
        ports:
        - containerPort: 9898
          protocol: TCP
          name: exporter
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: E2E_METRICS_PIPELINE_ID
          value: "gcp-101" # change as per env
        - name: E2E_METRICS_COVERAGE_NAME
          value: "oep-e2e-gcp-coverage" # change as per env
        - name: E2E_METRICS_RUN_ID
          value: "run-101" # change as per env
        volumeMounts:
        - name: metac
          mountPath: /etc/config/metac
        - name: metrics
          mountPath: /etc/config/e2e-metrics
      volumes:
      - name: metac
        configMap:
          name: metac-config-test
      - name: metrics
        configMap:
          name: metrics-config-test
---